-- ============================================================================
-- Migration: split "routes" (one departure time each) into "routes" +
-- "trips" (one route, many departure times).
--
-- Run this ONCE against your existing database (the one your app is
-- already using) - it upgrades the schema in place and keeps all your
-- existing tickets and testimonials pointed at the right rows. It does NOT
-- touch users, testimonials, contact_messages, or sessions.
--
-- Usage:
--   mysql -u root -p shuttle_bus_db < migrate_routes_to_trips.sql
--
-- Safe to run on a fresh database too (e.g. one just created from the old
-- schema.sql) - it simply has nothing to migrate in that case.
-- ============================================================================

USE shuttle_bus_db;

-- 1. Create the new trips table - one row per existing route, carrying over
--    that route's old departure_time. At this point every route still maps
--    1:1 to exactly one trip, which is what step 3 below relies on.
CREATE TABLE IF NOT EXISTS trips (
  id INT AUTO_INCREMENT PRIMARY KEY,
  route_id INT NOT NULL,
  departure_time VARCHAR(20) NOT NULL,
  FOREIGN KEY (route_id) REFERENCES routes(id),
  UNIQUE KEY uniq_route_departure (route_id, departure_time)
);

INSERT INTO trips (route_id, departure_time)
SELECT id, departure_time FROM routes;

-- 2. Add the new trip_id column to tickets, then fill it in using the 1:1
--    route->trip mapping created in step 1 (each ticket's old route_id now
--    maps to exactly one trip_id).
ALTER TABLE tickets ADD COLUMN trip_id INT NULL AFTER route_id;

UPDATE tickets t
JOIN trips tr ON tr.route_id = t.route_id
SET t.trip_id = tr.id;

-- 3. Drop the old route_id column from tickets. Its foreign key constraint
--    name is auto-generated by MySQL/MariaDB and can differ between
--    installs, so look it up from information_schema instead of hardcoding
--    a name that might not match yours.
SET @fk_name = (
  SELECT CONSTRAINT_NAME
  FROM information_schema.KEY_COLUMN_USAGE
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'tickets'
    AND COLUMN_NAME = 'route_id'
    AND REFERENCED_TABLE_NAME = 'routes'
  LIMIT 1
);
SET @drop_fk_sql = CONCAT('ALTER TABLE tickets DROP FOREIGN KEY ', @fk_name);
PREPARE drop_fk_stmt FROM @drop_fk_sql;
EXECUTE drop_fk_stmt;
DEALLOCATE PREPARE drop_fk_stmt;

ALTER TABLE tickets DROP COLUMN route_id;
ALTER TABLE tickets MODIFY trip_id INT NOT NULL;
ALTER TABLE tickets ADD FOREIGN KEY (trip_id) REFERENCES trips(id);

-- 4. Routes no longer carry a single departure time - that now lives on
--    trips instead.
ALTER TABLE routes DROP COLUMN departure_time;

-- Done. Each route that used to have exactly one departure time now has
-- exactly one trip with that time - nothing changes for existing bookings.
-- To give a route more departure times, add more rows to `trips` (or use
-- the new "+ Add departure time" button in /admin/routes.php).
